export const commitmentABI = [
  {
    type: 'event',
    name: 'CommitmentCreated',
    inputs: [
      { name: 'commitmentId', type: 'bytes32', indexed: true },
      { name: 'user', type: 'address', indexed: true },
      { name: 'distanceGoal', type: 'uint256', indexed: false },
      { name: 'stepGoal', type: 'uint256', indexed: false },
      { name: 'stakeAmount', type: 'uint256', indexed: false },
      { name: 'deadline', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'CommitmentCompleted',
    inputs: [
      { name: 'commitmentId', type: 'bytes32', indexed: true },
      { name: 'user', type: 'address', indexed: true },
      { name: 'bonusEarned', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'CommitmentCancelled',
    inputs: [
      { name: 'commitmentId', type: 'bytes32', indexed: true },
      { name: 'user', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'CommitmentForfeited',
    inputs: [
      { name: 'commitmentId', type: 'bytes32', indexed: true },
      { name: 'user', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'function',
    name: 'createCommitment',
    stateMutability: 'payable',
    inputs: [
      { name: 'distanceGoalMeters', type: 'uint256' },
      { name: 'stepGoal', type: 'uint256' },
      { name: 'timeWindowSeconds', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelCommitment',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'commitmentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'completeCommitment',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'commitmentId', type: 'bytes32' },
      { name: 'actualDistance', type: 'uint256' },
      { name: 'actualSteps', type: 'uint256' },
      { name: 'proofNonce', type: 'bytes32' },
      { name: 'signature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'forfeitExpiredCommitment',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'commitmentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getCommitment',
    stateMutability: 'view',
    inputs: [{ name: 'commitmentId', type: 'bytes32' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'user', type: 'address' },
          { name: 'distanceGoal', type: 'uint256' },
          { name: 'stepGoal', type: 'uint256' },
          { name: 'stakeAmount', type: 'uint256' },
          { name: 'deadline', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'completed', type: 'bool' },
          { name: 'cancelled', type: 'bool' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getActiveCommitmentId',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'activeCommitment',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'MIN_STAKE',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'verifier',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
] as const
